version: "3"
services:

  flask:
    image: smartlab/flask
    volumes:
        - ./app:/app
        - flask-lib:/usr/lib/python3.6/site-packages
    command: 
        - compose

  uwsgi:
    image: smartlab/uwsgi
    volumes:
        - ./app:/app
        - flask-lib:/usr/lib/python3.6/site-packages
    environment:
        - PYTHONPATH=/app:/usr/lib/python3.6/site-packages
    networks:
      - backend
    depends_on:
      - flask

  nginx:
    image: smartlab/nginx
    ports:
      - "5000:80"
    volumes:
      - ./nginx.vh.default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - frontend
      - backend
    depends_on:
      - uwsgi
      - flask

networks:
  frontend:
  backend:

volumes:
  flask-lib:
